default:
    image: registry.gitlab.tugraz.at/f23b736137140d66/mbpq

stages:
    - build
    - test
    - integration-test

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
    artifacts:
        paths: [gl-code-quality-report.json]

build-job:
    stage: build
    script:
        - pip3 install -r requirements.txt
        - pip3 install .

test-job:
    stage: test
    before_script:
        - pip3 install -e .
    script:
        - pytest --junitxml results_unittests_LinOp.xml --cov=pyqmri test/unittests/test_LinearDataOperator.py
        - pytest --junitxml results_unittests_grad.xml --cov=pyqmri test/unittests/test_gradient.py
        - pytest --junitxml results_unittests_symgrad.xml --cov=pyqmri test/unittests/test_symmetrized_gradient.py
    artifacts: 
        paths:
            - /*.xml

integration-job:
    stage: integration-test
    before_script:
        - pip3 install -e .
    script:
        - ipcluster start&
        - pytest --junitxml results_integrationtests_single_slice.xml --cov=pyqmri --integration-cover test/integrationtests/test_integration_test_single_slice.py
        - pytest --junitxml results_integrationtests_single_slice.xml --cov=pyqmri --integration-cover test/integrationtests/test_integration_test_multi_slice.py
        - ipcluster stop&
    artifacts: 
        paths:
            - /*.xml

    
